readingDataPointsFilters:
  - MinDistDataPointsFilter:
      dim: -1
      minDist: 1.0
  - RemoveNaNDataPointsFilter

referenceDataPointsFilters:
  - MinDistDataPointsFilter:
      dim: -1
      minDist: 1.0
  - RemoveNaNDataPointsFilter

matcher:
  KDTreeMatcher:
    knn: 1

outlierFilters:
  - TrimmedDistOutlierFilter:
      ratio: 0.9

errorMinimizer:
  PointToPointErrorMinimizer

transformationCheckers:
  - CounterTransformationChecker:
      maxIterationCount: 10
  - DifferentialTransformationChecker:
      minDiffRotErr: 0.001
      minDiffTransErr: 0.01
      smoothLength: 4

inspector:
  NullInspector

logger:
  NullLogger
